version: "2.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./errorlogs:/root/errorlogs
      - ./tokens:/root/tokens
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    # ports:
    #   - 0.0.0.0:5432:5432
    volumes:
      - twitchbutlerbot_pg_data:/var/lib/postgresql/data
      - ./sqlfiles:/root/sqlfiles
    restart: unless-stopped
    env_file:
      - .env
  redis:
    image: redis:7-alpine
    volumes:
      - twitchbutlerbot_redis_data:/data
    restart: unless-stopped

  # pgadmin4:
  #   image: dpage/pgadmin4
  #   restart: unless-stopped
  #   ports:
  #     - 8081:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  twitchbutlerbot_pg_data:
  twitchbutlerbot_redis_data:
