version: "2.4"

services:
  twitch-butler-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tokens:/root/tokens
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    # ports:
    #   - 5432:5432
    volumes:
      - twitchbutlerbot_pg_data:/var/lib/postgresql/data
      - ./sqlfiles:/root/sqlfiles
    restart: unless-stopped
    env_file:
      - .env

volumes:
  twitchbutlerbot_pg_data:
