version: "2.4"

services:
  twitch-butler-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tokens:/root/tokens
    restart: unless-stopped
    env_file:
      - .env
